import { computed, Injectable, signal } from '@angular/core';
import {
  ComponentThemeConfig,
  DEFAULT_GLOBAL_THEME,
  DEFAULT_IONIC_COLORS,
  GlobalThemeConfig,
  IONIC_COLOR_NAMES,
  IONIC_COMPONENTS,
  IonicColorName,
  ThemeMode,
} from '../models/theme.model';
import { generateIonicColorVariables } from '../utils/color.utils';

@Injectable({ providedIn: 'root' })
export class ThemeService {
  readonly mode = signal<ThemeMode>('light');
  readonly globalTheme = signal<GlobalThemeConfig>({ ...DEFAULT_GLOBAL_THEME });
  readonly componentThemes = signal<ComponentThemeConfig[]>(
    structuredClone(IONIC_COMPONENTS)
  );

  readonly generatedCss = computed(() => this.buildCss());

  updateColor(name: IonicColorName, value: string): void {
    this.globalTheme.update((theme) => ({
      ...theme,
      colors: { ...theme.colors, [name]: value },
    }));
  }

  updateGlobalProperty(
    key: keyof Omit<GlobalThemeConfig, 'colors'>,
    value: string
  ): void {
    this.globalTheme.update((theme) => ({
      ...theme,
      [key]: value,
    }));
  }

  updateComponentVariable(
    componentName: string,
    variableName: string,
    value: string
  ): void {
    this.componentThemes.update((themes) =>
      themes.map((theme) => {
        if (theme.componentName !== componentName) return theme;
        return {
          ...theme,
          variables: theme.variables.map((v) =>
            v.name === variableName ? { ...v, value } : v
          ),
        };
      })
    );
  }

  resetColors(): void {
    this.globalTheme.set({ ...DEFAULT_GLOBAL_THEME });
  }

  resetComponent(componentName: string): void {
    this.componentThemes.update((themes) =>
      themes.map((theme) => {
        if (theme.componentName !== componentName) return theme;
        const original = IONIC_COMPONENTS.find(
          (c) => c.componentName === componentName
        );
        return original ? structuredClone(original) : theme;
      })
    );
  }

  resetAll(): void {
    this.globalTheme.set({ ...DEFAULT_GLOBAL_THEME });
    this.componentThemes.set(structuredClone(IONIC_COMPONENTS));
  }

  private buildCss(): string {
    const theme = this.globalTheme();
    const components = this.componentThemes();
    const lines: string[] = [];

    lines.push('/**');
    lines.push(' * Ionic Theme - Generated by Ionic Theme Builder');
    lines.push(` * Generated on: ${new Date().toISOString().split('T')[0]}`);
    lines.push(' */');
    lines.push('');

    // Global :root variables
    lines.push(':root {');
    lines.push('  /* Global Colors */');

    for (const name of IONIC_COLOR_NAMES) {
      const hex = theme.colors[name] ?? DEFAULT_IONIC_COLORS[name];
      const vars = generateIonicColorVariables(name, hex);
      lines.push('');
      lines.push(`  /** ${name} **/`);
      for (const [varName, varValue] of Object.entries(vars)) {
        lines.push(`  ${varName}: ${varValue};`);
      }
    }

    lines.push('');
    lines.push('  /* Global Theme Variables */');
    lines.push(`  --ion-background-color: ${theme.backgroundColor};`);
    lines.push(`  --ion-text-color: ${theme.textColor};`);
    lines.push(`  --ion-font-family: ${theme.fontFamily};`);
    lines.push(`  --ion-toolbar-background: ${theme.toolbarBackground};`);
    lines.push(`  --ion-toolbar-color: ${theme.toolbarColor};`);
    lines.push(`  --ion-item-background: ${theme.itemBackground};`);
    lines.push(`  --ion-card-background: ${theme.cardBackground};`);
    lines.push('}');

    // Per-component variables
    const hasComponentOverrides = components.some((c) =>
      c.variables.some((v) => v.value !== v.defaultValue)
    );

    if (hasComponentOverrides) {
      lines.push('');
      lines.push('/* Component-Specific Overrides */');

      for (const component of components) {
        const overrides = component.variables.filter(
          (v) => v.value !== v.defaultValue
        );
        if (overrides.length === 0) continue;

        lines.push('');
        lines.push(`${component.componentName} {`);
        for (const variable of overrides) {
          lines.push(`  ${variable.name}: ${variable.value};`);
        }
        lines.push('}');
      }
    }

    return lines.join('\n');
  }
}
