import { computed, Injectable, signal } from '@angular/core';
import {
  ComponentThemeConfig,
  DarkModeConfig,
  DarkModeStrategy,
  DEFAULT_DARK_THEME,
  DEFAULT_GLOBAL_THEME,
  DEFAULT_IONIC_COLORS,
  GlobalThemeConfig,
  IONIC_COLOR_NAMES,
  IONIC_COMPONENTS,
  IonicColorName,
  IonicMode,
  ThemeMode,
} from '../models/theme.model';
import {
  generateIonicColorVariables,
  generateSteppedColors,
  hexToRgbString,
} from '../utils/color.utils';

@Injectable({ providedIn: 'root' })
export class ThemeService {
  readonly mode = signal<ThemeMode>('light');
  readonly globalMode = signal<IonicMode>('all');
  readonly globalTheme = signal<GlobalThemeConfig>({ ...DEFAULT_GLOBAL_THEME });
  readonly darkTheme = signal<DarkModeConfig>(structuredClone(DEFAULT_DARK_THEME));
  readonly componentThemes = signal<ComponentThemeConfig[]>(
    structuredClone(IONIC_COMPONENTS)
  );

  readonly generatedCss = computed(() => this.buildCss());

  updateColor(name: IonicColorName, value: string): void {
    this.globalTheme.update((theme) => ({
      ...theme,
      colors: { ...theme.colors, [name]: value },
    }));
  }

  updateGlobalProperty(
    key: keyof Omit<GlobalThemeConfig, 'colors'>,
    value: string
  ): void {
    this.globalTheme.update((theme) => ({
      ...theme,
      [key]: value,
    }));
  }

  // Dark mode methods
  toggleDarkMode(enabled: boolean): void {
    this.darkTheme.update((t) => ({ ...t, enabled }));
  }

  updateDarkStrategy(strategy: DarkModeStrategy): void {
    this.darkTheme.update((t) => ({ ...t, strategy }));
  }

  updateDarkColor(name: IonicColorName, value: string): void {
    this.darkTheme.update((t) => ({
      ...t,
      colors: { ...t.colors, [name]: value },
    }));
  }

  updateDarkProperty(
    key: keyof Omit<DarkModeConfig, 'colors' | 'enabled' | 'strategy'>,
    value: string
  ): void {
    this.darkTheme.update((t) => ({ ...t, [key]: value }));
  }

  updateComponentVariable(
    componentName: string,
    variableName: string,
    value: string
  ): void {
    this.componentThemes.update((themes) =>
      themes.map((theme) => {
        if (theme.componentName !== componentName) return theme;
        return {
          ...theme,
          variables: theme.variables.map((v) =>
            v.name === variableName ? { ...v, value } : v
          ),
        };
      })
    );
  }

  resetColors(): void {
    this.globalTheme.set({ ...DEFAULT_GLOBAL_THEME });
  }

  resetDarkColors(): void {
    this.darkTheme.set(structuredClone(DEFAULT_DARK_THEME));
  }

  resetComponent(componentName: string): void {
    this.componentThemes.update((themes) =>
      themes.map((theme) => {
        if (theme.componentName !== componentName) return theme;
        const original = IONIC_COMPONENTS.find(
          (c) => c.componentName === componentName
        );
        return original ? structuredClone(original) : theme;
      })
    );
  }

  resetAll(): void {
    this.globalTheme.set({ ...DEFAULT_GLOBAL_THEME });
    this.darkTheme.set(structuredClone(DEFAULT_DARK_THEME));
    this.componentThemes.set(structuredClone(IONIC_COMPONENTS));
    this.globalMode.set('all');
  }

  setGlobalMode(mode: IonicMode): void {
    this.globalMode.set(mode);
  }

  updateComponentMode(componentName: string, mode: IonicMode): void {
    this.componentThemes.update((themes) =>
      themes.map((theme) =>
        theme.componentName === componentName ? { ...theme, mode } : theme
      )
    );
  }

  private buildCss(): string {
    const theme = this.globalTheme();
    const dark = this.darkTheme();
    const components = this.componentThemes();
    const mode = this.globalMode();
    const lines: string[] = [];

    lines.push('/**');
    lines.push(' * Ionic Theme - Generated by Ionic Theme Builder');
    lines.push(` * Generated on: ${new Date().toISOString().split('T')[0]}`);
    lines.push(` * Mode: ${mode === 'all' ? 'All platforms' : mode.toUpperCase()}`);
    lines.push(' */');
    lines.push('');

    // Root selector based on global mode
    const rootSelector = this.getRootSelector(mode);
    lines.push(`${rootSelector} {`);
    lines.push('  /* Ionic Color Variables */');

    for (const name of IONIC_COLOR_NAMES) {
      const hex = theme.colors[name] ?? DEFAULT_IONIC_COLORS[name];
      const vars = generateIonicColorVariables(name, hex);
      lines.push('');
      lines.push(`  /** ${name} **/`);
      for (const [varName, varValue] of Object.entries(vars)) {
        lines.push(`  ${varName}: ${varValue};`);
      }
    }

    lines.push('');
    lines.push('  /* Application Colors */');
    lines.push(`  --ion-background-color: ${theme.backgroundColor};`);
    lines.push(`  --ion-background-color-rgb: ${hexToRgbString(theme.backgroundColor)};`);
    lines.push(`  --ion-text-color: ${theme.textColor};`);
    lines.push(`  --ion-text-color-rgb: ${hexToRgbString(theme.textColor)};`);
    lines.push(`  --ion-font-family: ${theme.fontFamily};`);
    lines.push('');
    lines.push('  /* Toolbar */');
    lines.push(`  --ion-toolbar-background: ${theme.toolbarBackground};`);
    lines.push(`  --ion-toolbar-color: ${theme.toolbarColor};`);
    lines.push(`  --ion-toolbar-border-color: ${theme.toolbarBorderColor};`);
    lines.push('');
    lines.push('  /* Items */');
    lines.push(`  --ion-item-background: ${theme.itemBackground};`);
    lines.push(`  --ion-item-border-color: ${theme.itemBorderColor};`);
    lines.push('');
    lines.push('  /* Cards */');
    lines.push(`  --ion-card-background: ${theme.cardBackground};`);
    lines.push('');
    lines.push('  /* Tab Bar */');
    lines.push(`  --ion-tab-bar-background: ${theme.tabBarBackground};`);
    lines.push(`  --ion-tab-bar-border-color: ${theme.tabBarBorderColor};`);
    lines.push(`  --ion-tab-bar-color: ${theme.tabBarColor};`);
    lines.push(`  --ion-tab-bar-color-selected: ${theme.tabBarColorSelected};`);
    lines.push('');
    lines.push('  /* Other */');
    lines.push(`  --ion-backdrop-color: ${theme.backdropColor};`);
    lines.push(`  --ion-backdrop-opacity: ${theme.backdropOpacity};`);
    lines.push(`  --ion-overlay-background-color: ${theme.overlayBackground};`);
    lines.push(`  --ion-border-color: ${theme.borderColor};`);
    lines.push(`  --ion-placeholder-color: ${theme.placeholderColor};`);

    // Stepped colors
    const bgSteps = generateSteppedColors(theme.backgroundColor, theme.textColor);
    const textSteps = generateSteppedColors(theme.textColor, theme.backgroundColor);
    lines.push('');
    lines.push('  /* Stepped Background Colors */');
    for (const [step, color] of Object.entries(bgSteps)) {
      lines.push(`  --ion-background-color-step-${step}: ${color};`);
    }
    lines.push('');
    lines.push('  /* Stepped Text Colors */');
    for (const [step, color] of Object.entries(textSteps)) {
      lines.push(`  --ion-text-color-step-${step}: ${color};`);
    }

    lines.push('}');

    // Dark mode
    if (dark.enabled) {
      lines.push('');
      lines.push('/* Dark Mode */');

      const darkSelector = this.getDarkSelector(dark.strategy, mode);
      const darkSelectorEnd = this.getDarkSelectorEnd(dark.strategy);

      lines.push(darkSelector);

      for (const name of IONIC_COLOR_NAMES) {
        const hex = dark.colors[name];
        if (!hex) continue;
        const vars = generateIonicColorVariables(name, hex);
        lines.push('');
        lines.push(`  /** ${name} **/`);
        for (const [varName, varValue] of Object.entries(vars)) {
          lines.push(`  ${varName}: ${varValue};`);
        }
      }

      lines.push('');
      lines.push('  /* Dark Application Colors */');
      lines.push(`  --ion-background-color: ${dark.backgroundColor};`);
      lines.push(`  --ion-background-color-rgb: ${hexToRgbString(dark.backgroundColor)};`);
      lines.push(`  --ion-text-color: ${dark.textColor};`);
      lines.push(`  --ion-text-color-rgb: ${hexToRgbString(dark.textColor)};`);
      lines.push('');
      lines.push(`  --ion-toolbar-background: ${dark.toolbarBackground};`);
      lines.push(`  --ion-toolbar-color: ${dark.toolbarColor};`);
      lines.push(`  --ion-toolbar-border-color: ${dark.toolbarBorderColor};`);
      lines.push(`  --ion-item-background: ${dark.itemBackground};`);
      lines.push(`  --ion-item-border-color: ${dark.itemBorderColor};`);
      lines.push(`  --ion-card-background: ${dark.cardBackground};`);
      lines.push(`  --ion-border-color: ${dark.borderColor};`);
      lines.push(`  --ion-tab-bar-background: ${dark.tabBarBackground};`);
      lines.push(`  --ion-tab-bar-color: ${dark.tabBarColor};`);
      lines.push(`  --ion-tab-bar-color-selected: ${dark.tabBarColorSelected};`);

      // Dark stepped colors
      const darkBgSteps = generateSteppedColors(dark.backgroundColor, dark.textColor);
      const darkTextSteps = generateSteppedColors(dark.textColor, dark.backgroundColor);
      lines.push('');
      lines.push('  /* Stepped Background Colors (Dark) */');
      for (const [step, color] of Object.entries(darkBgSteps)) {
        lines.push(`  --ion-background-color-step-${step}: ${color};`);
      }
      lines.push('');
      lines.push('  /* Stepped Text Colors (Dark) */');
      for (const [step, color] of Object.entries(darkTextSteps)) {
        lines.push(`  --ion-text-color-step-${step}: ${color};`);
      }

      lines.push(darkSelectorEnd);
    }

    // Per-component variables with mode support
    const componentsToOutput = components.filter((c) =>
      c.mode !== 'all' || c.variables.some((v) => v.value !== v.defaultValue)
    );

    if (componentsToOutput.length > 0) {
      lines.push('');
      lines.push('/* Component-Specific Overrides */');

      for (const component of componentsToOutput) {
        const overrides = component.variables.filter(
          (v) => v.value !== v.defaultValue
        );
        // If mode is non-default, always output the block (even with defaults)
        const variablesToOutput = component.mode !== 'all'
          ? component.variables
          : overrides;
        if (variablesToOutput.length === 0) continue;

        const selector = this.getComponentSelector(component.componentName, component.mode);
        lines.push('');
        lines.push(`${selector} {`);
        for (const variable of variablesToOutput) {
          lines.push(`  ${variable.name}: ${variable.value};`);
        }
        lines.push('}');
      }
    }

    return lines.join('\n');
  }

  private getRootSelector(mode: IonicMode): string {
    switch (mode) {
      case 'all':
        return ':root';
      case 'ios':
        return ':root.ios';
      case 'md':
        return ':root.md';
    }
  }

  private getComponentSelector(componentName: string, mode: IonicMode): string {
    switch (mode) {
      case 'all':
        return componentName;
      case 'ios':
        return `${componentName}.ios`;
      case 'md':
        return `${componentName}.md`;
    }
  }

  private getDarkSelector(strategy: DarkModeStrategy, mode: IonicMode): string {
    const rootSelector = mode === 'all' ? ':root' : `:root.${mode}`;
    switch (strategy) {
      case 'always':
        return `${rootSelector} {`;
      case 'system':
        return `@media (prefers-color-scheme: dark) {\n  ${rootSelector} {`;
      case 'class':
        return `${rootSelector}.ion-palette-dark {`;
    }
  }

  private getDarkSelectorEnd(strategy: DarkModeStrategy): string {
    switch (strategy) {
      case 'always':
        return '}';
      case 'system':
        return '  }\n}';
      case 'class':
        return '}';
    }
  }
}
