import { DarkModeConfig, GlobalThemeConfig } from './theme.model';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  light: GlobalThemeConfig;
  dark: Omit<DarkModeConfig, 'enabled' | 'strategy'>;
}

export const THEME_PRESETS: ThemePreset[] = [
  // ─── Default Ionic ───
  {
    id: 'default',
    name: 'Ionic Default',
    description: 'Standard Ionic Framework theme',
    light: {
      colors: {
        primary: '#4c8dff',
        secondary: '#5260ff',
        tertiary: '#6a64ff',
        success: '#2dd55b',
        warning: '#ffc409',
        danger: '#c5000f',
        dark: '#2f2f2f',
        medium: '#808080',
        light: '#f2f2f2',
      },
      backgroundColor: '#ffffff',
      textColor: '#000000',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      toolbarBackground: '#ffffff',
      toolbarColor: '#000000',
      toolbarBorderColor: '#c8c7cc',
      itemBackground: '#ffffff',
      itemBorderColor: '#c8c7cc',
      cardBackground: '#ffffff',
      backdropColor: '#000000',
      backdropOpacity: '0.32',
      overlayBackground: '#ffffff',
      borderColor: '#c8c7cc',
      tabBarBackground: '#f8f8f8',
      tabBarBorderColor: '#c8c7cc',
      tabBarColor: '#8c8c8c',
      tabBarColorSelected: '#4c8dff',
      placeholderColor: '#999999',
    },
    dark: {
      colors: {
        primary: '#4c8dff',
        secondary: '#5260ff',
        tertiary: '#6a64ff',
        success: '#2dd55b',
        warning: '#ffc409',
        danger: '#cf3c4f',
        dark: '#f4f5f8',
        medium: '#989aa2',
        light: '#222428',
      },
      backgroundColor: '#121212',
      textColor: '#f0f0f0',
      toolbarBackground: '#1f1f1f',
      toolbarColor: '#f0f0f0',
      toolbarBorderColor: '#3a3a3a',
      itemBackground: '#1e1e1e',
      itemBorderColor: '#3a3a3a',
      cardBackground: '#2a2a2a',
      borderColor: '#3a3a3a',
      tabBarBackground: '#1f1f1f',
      tabBarColor: '#989aa2',
      tabBarColorSelected: '#4c8dff',
    },
  },

  // ─── Apple Glass (Modern translucent) ───
  {
    id: 'apple-glass',
    name: 'Apple Glass',
    description: 'Modern frosted glass aesthetic inspired by visionOS',
    light: {
      colors: {
        primary: '#007AFF',
        secondary: '#5856D6',
        tertiary: '#AF52DE',
        success: '#30D158',
        warning: '#FF9F0A',
        danger: '#FF3B30',
        dark: '#1C1C1E',
        medium: '#8E8E93',
        light: '#F2F2F7',
      },
      backgroundColor: '#F2F2F7',
      textColor: '#1C1C1E',
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", sans-serif',
      toolbarBackground: 'rgba(255, 255, 255, 0.72)',
      toolbarColor: '#1C1C1E',
      toolbarBorderColor: 'rgba(60, 60, 67, 0.12)',
      itemBackground: 'rgba(255, 255, 255, 0.8)',
      itemBorderColor: 'rgba(60, 60, 67, 0.08)',
      cardBackground: 'rgba(255, 255, 255, 0.85)',
      backdropColor: '#000000',
      backdropOpacity: '0.4',
      overlayBackground: 'rgba(255, 255, 255, 0.9)',
      borderColor: 'rgba(60, 60, 67, 0.12)',
      tabBarBackground: 'rgba(249, 249, 249, 0.94)',
      tabBarBorderColor: 'rgba(60, 60, 67, 0.1)',
      tabBarColor: '#8E8E93',
      tabBarColorSelected: '#007AFF',
      placeholderColor: '#8E8E93',
    },
    dark: {
      colors: {
        primary: '#0A84FF',
        secondary: '#5E5CE6',
        tertiary: '#BF5AF2',
        success: '#30D158',
        warning: '#FFD60A',
        danger: '#FF453A',
        dark: '#F2F2F7',
        medium: '#8E8E93',
        light: '#1C1C1E',
      },
      backgroundColor: '#000000',
      textColor: '#F2F2F7',
      toolbarBackground: 'rgba(30, 30, 30, 0.72)',
      toolbarColor: '#F2F2F7',
      toolbarBorderColor: 'rgba(84, 84, 88, 0.36)',
      itemBackground: 'rgba(44, 44, 46, 0.6)',
      itemBorderColor: 'rgba(84, 84, 88, 0.36)',
      cardBackground: 'rgba(44, 44, 46, 0.7)',
      borderColor: 'rgba(84, 84, 88, 0.36)',
      tabBarBackground: 'rgba(30, 30, 30, 0.9)',
      tabBarColor: '#8E8E93',
      tabBarColorSelected: '#0A84FF',
    },
  },

  // ─── Material You (Google Dynamic Color) ───
  {
    id: 'material-you',
    name: 'Material You',
    description: 'Google Material Design 3 with dynamic color',
    light: {
      colors: {
        primary: '#6750A4',
        secondary: '#625B71',
        tertiary: '#7D5260',
        success: '#386A20',
        warning: '#7D5700',
        danger: '#BA1A1A',
        dark: '#1C1B1F',
        medium: '#79747E',
        light: '#FFFBFE',
      },
      backgroundColor: '#FFFBFE',
      textColor: '#1C1B1F',
      fontFamily: '"Google Sans", "Roboto", sans-serif',
      toolbarBackground: '#FFFBFE',
      toolbarColor: '#1C1B1F',
      toolbarBorderColor: '#E7E0EC',
      itemBackground: '#FFFBFE',
      itemBorderColor: '#E7E0EC',
      cardBackground: '#F7F2FA',
      backdropColor: '#000000',
      backdropOpacity: '0.32',
      overlayBackground: '#FFFBFE',
      borderColor: '#E7E0EC',
      tabBarBackground: '#FFFBFE',
      tabBarBorderColor: '#E7E0EC',
      tabBarColor: '#79747E',
      tabBarColorSelected: '#6750A4',
      placeholderColor: '#79747E',
    },
    dark: {
      colors: {
        primary: '#D0BCFF',
        secondary: '#CCC2DC',
        tertiary: '#EFB8C8',
        success: '#A8DB8F',
        warning: '#FFBF47',
        danger: '#FFB4AB',
        dark: '#E6E1E5',
        medium: '#CAC4D0',
        light: '#1C1B1F',
      },
      backgroundColor: '#1C1B1F',
      textColor: '#E6E1E5',
      toolbarBackground: '#2B2930',
      toolbarColor: '#E6E1E5',
      toolbarBorderColor: '#49454F',
      itemBackground: '#2B2930',
      itemBorderColor: '#49454F',
      cardBackground: '#332D41',
      borderColor: '#49454F',
      tabBarBackground: '#2B2930',
      tabBarColor: '#CAC4D0',
      tabBarColorSelected: '#D0BCFF',
    },
  },

  // ─── Retro Terminal (Old computer) ───
  {
    id: 'retro-terminal',
    name: 'Retro Terminal',
    description: 'Vintage CRT terminal with phosphor green',
    light: {
      colors: {
        primary: '#00FF41',
        secondary: '#00D4AA',
        tertiary: '#FFB000',
        success: '#00FF41',
        warning: '#FFB000',
        danger: '#FF0040',
        dark: '#0D0D0D',
        medium: '#33FF77',
        light: '#0A1A0A',
      },
      backgroundColor: '#0D0D0D',
      textColor: '#00FF41',
      fontFamily: '"Courier New", "Lucida Console", "Consolas", monospace',
      toolbarBackground: '#0A1A0A',
      toolbarColor: '#00FF41',
      toolbarBorderColor: '#003B00',
      itemBackground: '#0A1A0A',
      itemBorderColor: '#003B00',
      cardBackground: '#0F1F0F',
      backdropColor: '#000000',
      backdropOpacity: '0.8',
      overlayBackground: '#0D0D0D',
      borderColor: '#003B00',
      tabBarBackground: '#050F05',
      tabBarBorderColor: '#003B00',
      tabBarColor: '#008F11',
      tabBarColorSelected: '#00FF41',
      placeholderColor: '#006600',
    },
    dark: {
      colors: {
        primary: '#00FF41',
        secondary: '#00D4AA',
        tertiary: '#FFB000',
        success: '#00FF41',
        warning: '#FFB000',
        danger: '#FF0040',
        dark: '#00FF41',
        medium: '#33FF77',
        light: '#0A1A0A',
      },
      backgroundColor: '#000000',
      textColor: '#00FF41',
      toolbarBackground: '#050F05',
      toolbarColor: '#00FF41',
      toolbarBorderColor: '#003B00',
      itemBackground: '#050F05',
      itemBorderColor: '#003B00',
      cardBackground: '#0A1A0A',
      borderColor: '#003B00',
      tabBarBackground: '#020802',
      tabBarColor: '#006600',
      tabBarColorSelected: '#00FF41',
    },
  },

  // ─── Sunset Warmth ───
  {
    id: 'sunset-warmth',
    name: 'Sunset Warmth',
    description: 'Warm gradient tones inspired by golden hour',
    light: {
      colors: {
        primary: '#E8590C',
        secondary: '#D6336C',
        tertiary: '#AE3EC9',
        success: '#37B24D',
        warning: '#F59F00',
        danger: '#E03131',
        dark: '#2C2E33',
        medium: '#868E96',
        light: '#FFF5F5',
      },
      backgroundColor: '#FFFAF5',
      textColor: '#2C2E33',
      fontFamily: '"DM Sans", "Inter", sans-serif',
      toolbarBackground: '#FFFFFF',
      toolbarColor: '#2C2E33',
      toolbarBorderColor: '#FFE0CC',
      itemBackground: '#FFFFFF',
      itemBorderColor: '#FFE8D6',
      cardBackground: '#FFF8F1',
      backdropColor: '#2C2E33',
      backdropOpacity: '0.35',
      overlayBackground: '#FFFFFF',
      borderColor: '#FFE0CC',
      tabBarBackground: '#FFFAF5',
      tabBarBorderColor: '#FFE0CC',
      tabBarColor: '#868E96',
      tabBarColorSelected: '#E8590C',
      placeholderColor: '#ADB5BD',
    },
    dark: {
      colors: {
        primary: '#FF6B2B',
        secondary: '#F06595',
        tertiary: '#CC5DE8',
        success: '#51CF66',
        warning: '#FFD43B',
        danger: '#FF6B6B',
        dark: '#F8F9FA',
        medium: '#ADB5BD',
        light: '#212529',
      },
      backgroundColor: '#1A1110',
      textColor: '#FFF5F0',
      toolbarBackground: '#2A1F1E',
      toolbarColor: '#FFF5F0',
      toolbarBorderColor: '#4A3530',
      itemBackground: '#2A1F1E',
      itemBorderColor: '#4A3530',
      cardBackground: '#352825',
      borderColor: '#4A3530',
      tabBarBackground: '#1A1110',
      tabBarColor: '#ADB5BD',
      tabBarColorSelected: '#FF6B2B',
    },
  },

  // ─── Ocean Breeze ───
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Cool coastal palette with deep blues and seafoam',
    light: {
      colors: {
        primary: '#0077B6',
        secondary: '#00B4D8',
        tertiary: '#48CAE4',
        success: '#06D6A0',
        warning: '#FFD166',
        danger: '#EF476F',
        dark: '#023E58',
        medium: '#90A4AE',
        light: '#F0F8FF',
      },
      backgroundColor: '#F8FDFF',
      textColor: '#023E58',
      fontFamily: '"Plus Jakarta Sans", "Inter", sans-serif',
      toolbarBackground: '#FFFFFF',
      toolbarColor: '#023E58',
      toolbarBorderColor: '#B8E4F0',
      itemBackground: '#FFFFFF',
      itemBorderColor: '#D4EFF7',
      cardBackground: '#F0FAFF',
      backdropColor: '#023E58',
      backdropOpacity: '0.35',
      overlayBackground: '#FFFFFF',
      borderColor: '#B8E4F0',
      tabBarBackground: '#F8FDFF',
      tabBarBorderColor: '#B8E4F0',
      tabBarColor: '#90A4AE',
      tabBarColorSelected: '#0077B6',
      placeholderColor: '#90A4AE',
    },
    dark: {
      colors: {
        primary: '#48CAE4',
        secondary: '#00B4D8',
        tertiary: '#90E0EF',
        success: '#06D6A0',
        warning: '#FFD166',
        danger: '#EF476F',
        dark: '#CAF0F8',
        medium: '#90A4AE',
        light: '#03223B',
      },
      backgroundColor: '#03192A',
      textColor: '#E0F7FA',
      toolbarBackground: '#042C47',
      toolbarColor: '#E0F7FA',
      toolbarBorderColor: '#0A4A6B',
      itemBackground: '#042C47',
      itemBorderColor: '#0A4A6B',
      cardBackground: '#053555',
      borderColor: '#0A4A6B',
      tabBarBackground: '#031E33',
      tabBarColor: '#78909C',
      tabBarColorSelected: '#48CAE4',
    },
  },

  // ─── Midnight Purple ───
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    description: 'Rich purple hues with a luxurious dark feel',
    light: {
      colors: {
        primary: '#7C3AED',
        secondary: '#A855F7',
        tertiary: '#EC4899',
        success: '#10B981',
        warning: '#F59E0B',
        danger: '#EF4444',
        dark: '#1E1033',
        medium: '#9CA3AF',
        light: '#FAF5FF',
      },
      backgroundColor: '#FAF5FF',
      textColor: '#1E1033',
      fontFamily: '"Space Grotesk", "Inter", sans-serif',
      toolbarBackground: '#FFFFFF',
      toolbarColor: '#1E1033',
      toolbarBorderColor: '#E9D5FF',
      itemBackground: '#FFFFFF',
      itemBorderColor: '#F3E8FF',
      cardBackground: '#FDF4FF',
      backdropColor: '#1E1033',
      backdropOpacity: '0.4',
      overlayBackground: '#FFFFFF',
      borderColor: '#E9D5FF',
      tabBarBackground: '#FAF5FF',
      tabBarBorderColor: '#E9D5FF',
      tabBarColor: '#9CA3AF',
      tabBarColorSelected: '#7C3AED',
      placeholderColor: '#A78BFA',
    },
    dark: {
      colors: {
        primary: '#A78BFA',
        secondary: '#C084FC',
        tertiary: '#F472B6',
        success: '#34D399',
        warning: '#FBBF24',
        danger: '#F87171',
        dark: '#F3E8FF',
        medium: '#9CA3AF',
        light: '#1E1033',
      },
      backgroundColor: '#0F0720',
      textColor: '#F3E8FF',
      toolbarBackground: '#1A0E30',
      toolbarColor: '#F3E8FF',
      toolbarBorderColor: '#3B1F6E',
      itemBackground: '#1A0E30',
      itemBorderColor: '#3B1F6E',
      cardBackground: '#211540',
      borderColor: '#3B1F6E',
      tabBarBackground: '#0F0720',
      tabBarColor: '#7C6EA4',
      tabBarColorSelected: '#A78BFA',
    },
  },

  // ─── Nord ───
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic-inspired minimal palette by Arctic Ice Studio',
    light: {
      colors: {
        primary: '#5E81AC',
        secondary: '#81A1C1',
        tertiary: '#88C0D0',
        success: '#A3BE8C',
        warning: '#EBCB8B',
        danger: '#BF616A',
        dark: '#2E3440',
        medium: '#4C566A',
        light: '#ECEFF4',
      },
      backgroundColor: '#ECEFF4',
      textColor: '#2E3440',
      fontFamily: '"IBM Plex Sans", "Inter", sans-serif',
      toolbarBackground: '#E5E9F0',
      toolbarColor: '#2E3440',
      toolbarBorderColor: '#D8DEE9',
      itemBackground: '#E5E9F0',
      itemBorderColor: '#D8DEE9',
      cardBackground: '#E5E9F0',
      backdropColor: '#2E3440',
      backdropOpacity: '0.3',
      overlayBackground: '#ECEFF4',
      borderColor: '#D8DEE9',
      tabBarBackground: '#E5E9F0',
      tabBarBorderColor: '#D8DEE9',
      tabBarColor: '#4C566A',
      tabBarColorSelected: '#5E81AC',
      placeholderColor: '#4C566A',
    },
    dark: {
      colors: {
        primary: '#88C0D0',
        secondary: '#81A1C1',
        tertiary: '#5E81AC',
        success: '#A3BE8C',
        warning: '#EBCB8B',
        danger: '#BF616A',
        dark: '#ECEFF4',
        medium: '#D8DEE9',
        light: '#2E3440',
      },
      backgroundColor: '#2E3440',
      textColor: '#ECEFF4',
      toolbarBackground: '#3B4252',
      toolbarColor: '#ECEFF4',
      toolbarBorderColor: '#434C5E',
      itemBackground: '#3B4252',
      itemBorderColor: '#434C5E',
      cardBackground: '#3B4252',
      borderColor: '#434C5E',
      tabBarBackground: '#2E3440',
      tabBarColor: '#D8DEE9',
      tabBarColorSelected: '#88C0D0',
    },
  },

  // ─── Cyberpunk Neon ───
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'High-contrast neon-on-dark futuristic aesthetic',
    light: {
      colors: {
        primary: '#FF00FF',
        secondary: '#00FFFF',
        tertiary: '#FFFF00',
        success: '#39FF14',
        warning: '#FF6600',
        danger: '#FF0055',
        dark: '#0D0D0D',
        medium: '#666677',
        light: '#1A1A2E',
      },
      backgroundColor: '#0D0D1A',
      textColor: '#EAEAF2',
      fontFamily: '"Rajdhani", "Orbitron", "Share Tech Mono", monospace',
      toolbarBackground: '#12122A',
      toolbarColor: '#FF00FF',
      toolbarBorderColor: '#2A2A4A',
      itemBackground: '#12122A',
      itemBorderColor: '#2A2A4A',
      cardBackground: '#16163A',
      backdropColor: '#000000',
      backdropOpacity: '0.7',
      overlayBackground: '#12122A',
      borderColor: '#2A2A4A',
      tabBarBackground: '#0A0A18',
      tabBarBorderColor: '#2A2A4A',
      tabBarColor: '#666677',
      tabBarColorSelected: '#00FFFF',
      placeholderColor: '#444466',
    },
    dark: {
      colors: {
        primary: '#FF00FF',
        secondary: '#00FFFF',
        tertiary: '#FFFF00',
        success: '#39FF14',
        warning: '#FF6600',
        danger: '#FF0055',
        dark: '#EAEAF2',
        medium: '#8888AA',
        light: '#0D0D1A',
      },
      backgroundColor: '#050510',
      textColor: '#EAEAF2',
      toolbarBackground: '#0A0A1F',
      toolbarColor: '#FF00FF',
      toolbarBorderColor: '#1A1A3A',
      itemBackground: '#0A0A1F',
      itemBorderColor: '#1A1A3A',
      cardBackground: '#0F0F2A',
      borderColor: '#1A1A3A',
      tabBarBackground: '#050510',
      tabBarColor: '#5555AA',
      tabBarColorSelected: '#00FFFF',
    },
  },
];
